### ISSUE TITLE
Dead link for Latin Treebank Guidelines

### ISSUE THREAD

**Issue by diyclassics** [PerseusDL/treebank_data#22]
The link for "guidelines" in the following paragraph on the gh-pages branch is dead:

"The Latin Dependency Treebank

The Latin Dependency Treebank contains texts annotated according to the guidelines v. 1.3. The current release (v. 2.1) contains the following texts:"

 Please advise.

Also, related—is there an update version of the guidelines available for v. 2.1?

Thanks, PJB

**Comment by lcerrato** [comment]
@diyclassics 

See also #20

**Comment by lcerrato** [comment]
@diyclassics 
I can't answer the updated version guideline question but have created PR #23 to redirect the link.
The link itself does work but it's useless outside of Tufts as the server is now restricted to within Tufts' network.

**Comment by diyclassics** [comment]
Thanks for the clarification!—I'll close the issue tomorrow in case anyone (perhaps @gcelano) has an answer to question about updated guidelines.

**Comment by gcelano** [comment]
There is no update for the guidelines yet. The guidelines, as well as old material, are now saved here:
https://github.com/PerseusDL/treebank_data/tree/master/v1
