### ISSUE TITLE
some possible errors in beta code for Homer

### ISSUE THREAD

**Issue by bcrowell** [PerseusDL/treebank_data#30]
I went through the data for the Iliad and Odyssey and used cltk to convert the beta code to unicode, then went through the results with a ruby script to do some further processing, clean things up, and check for errors. There seem to be some cases where either there is an error in the beta code or else the beta code is not compatible with cltk's parser. Beta code seems to be a big, huge, complicated standard, so I'm not really sure if these are errors on your end, errors in the cltk parser, or cases where the cltk parser implemeted a smaller subset of beta code than you use. However, I thought I would show you what I had to do to finish cleaning up the cltk parser's output, and if you noticed things that looked like actual errors on your end, then you'd know.

Here is the ruby code I wrote that post-processed cltk's output:

```
def clean_up_greek(s)
  # some cases where cltk fails to convert beta code correctly, maybe because the beta code syntax wasn't legal:
  s = s.sub(/\((.)/) { $1.tr("αειουηω","ἁἑἱὁὑἡὡ") }
  s = s.sub(/\)(.)/) { $1.tr("αειουηω","ἀἐἰὀὐἠὠ") }
  s = s.sub(/(.)~/) { $1.tr("αιυηω","ᾶῖῦῆῶ") }
  s = s.sub(/\|/,'ϊ')
  s = s.sub(/\/(.)/) { $1.tr("αειουηω","άέίόύήώ") }
  s = s.sub(/σ$/,'ς').unicode_normalize(:nfc)
  s = s.sub(/θεοισ=ν/,'θεοῖσιν')
  s = s.sub(/ὀ=νοψ1/,'οἴνοπα1')
  s = s.sub(/π=ας/,'πᾶς')
  if s=~/[^[:alpha:]᾽[0-9]\?;]/ then die("word #{s} contains unexpected characters\n") end
  return s
end
```

**Comment by bcrowell** [comment]
I filed a corresponding issue for cltk: https://github.com/cltk/cltk/issues/1117

**Comment by gcelano** [comment]
The data have been converted into the Greek script a long time ago. Please, refer to the last release: https://github.com/PerseusDL/treebank_data/tree/master/v2.1/Greek

**Comment by bcrowell** [comment]
Oops, sorry, I misunderstood. I'll close this issue.
